## Exercici 1

Crea un Array numèric d’una dimensió, fes operacions de càlcul sobre ell. En concret: suma dels diferents valors, resta, fes la mitja, etc.

In [3]:
!pip install numpy 
# he instalat la llibreria numpy

In [ ]:
import numpy as np # Estem important la llibreria numpy y la anomenem np

arr = np.array([1,2,3,4,5]) #creem un array numèric d'una dimensió

suma = np.sum(arr) #suma dels valors en al array

resta = arr - 1 #resta dels valors al array restan un 1 a cada element

mitja = np.mean(arr)

print("He creat el seguent Array",arr)

print("La suma dels valors es", suma)

print("Array amb un 1 restat a cada element", resta)

print("La Mitja dels valors es", mitja)


He creat el seguent Array [1 2 3 4 5]
La suma dels valors es 15
Array amb un 1 restat a cada element [0 1 2 3 4]
La Mitja dels valors es 3.0


## Exercici 2

Crea una matriu (taula) quadrada NxN de nombres aleatoris entre el 0 i el 100.

In [ ]:
N = 3 #Aquest será el tamay de la matriu cuadrada

matriu = np.random.randint(0,100, size=(N,N)) #utilitza per generar números aleatoris en un rang especific.

print(matriu)

[[94 19 58]
 [12 88 77]
 [47 97 66]]


## Exercici 3

Crea una matriu (taula) de dues dimensions (NxM), i calcula els totals per fila i els totals per columna.

In [ ]:
N = 3
M = 4

matriu = np.random.randint(0,101, size=(N,M))

print(matriu) #Creem la taula de les dues dimensions, i l'he dit que dimensió "size" ha de tenir les variables N i M

#Creem una variable per sumar el total per files
total_per_files = np.sum(matriu, axis=1)

#ara creem una variable per calcular les totals per columna
total_per_colum = np.sum(matriu, axis=0)

print("El total per fila es", total_per_files)
print("El total per columnes es",total_per_colum)


[[ 99  83   6  43]
 [100  28   6  94]
 [ 52  76  82  77]]
El total per fila es [231 228 287]
El total per columnes es [251 187  94 214]


## Exercici 4

Calcula manualment el coeficient de correlació entre dos arrays numèrics creats per tu. Informa-te'n sobre els seus usos i interpretació. Pots fer un array amb les alçades de diferents persones i un altre array amb els pesos d'aquestes persones i mirar-ne la correlació.

In [18]:
# Definim les variables

alçada = np.array([1.70, 1.65, 1.66, 1.80, 1.67, 1.71])
pes = np.array([60, 70, 72, 69, 75, 80])

# Calculem el coeficient de correlació amb la funció a.corref

coeficient_correlacio = np.corrcoef(alçada, pes)[0, 1]

print("El coeficient de correlació:", coeficient_correlacio)


El coeficient de correlació: -0.11968783390489648
